// This file has been autogenerated from a class added in the UI designer.

using System;
using NDB.Covid19.Enums;
using NDB.Covid19.iOS.Utils;
using NDB.Covid19.Utils;
using NDB.Covid19.ViewModels;
using UIKit;
using Xamarin.Essentials;
using static NDB.Covid19.ViewModels.DiseaseRateViewModel;

namespace NDB.Covid19.iOS.Views.DiseaseRate
{
    public partial class DiseaseRateViewController : BaseViewController
    {
        public DiseaseRateViewController(IntPtr handle) : base(handle)
        {
        }

        public static DiseaseRateViewController Create()
        {
            UIStoryboard storyboard = UIStoryboard.FromName("DiseaseRate", null);
            DiseaseRateViewController vc = (DiseaseRateViewController) storyboard.InstantiateInitialViewController();
            vc.ModalPresentationStyle = UIModalPresentationStyle.FullScreen;
            return vc;
        }

        public static UINavigationController GetDiseaseRatePageControllerInNavigationController()
        {
            UIViewController vc = Create();
            UINavigationController navigationController = new UINavigationController(vc);
            navigationController.SetNavigationBarHidden(true, false);
            navigationController.ModalPresentationStyle = UIModalPresentationStyle.FullScreen;
            return navigationController;
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            SetStyling();
            MessagingCenter.Subscribe<object>(this, MessagingCenterKeys.KEY_APP_RETURNS_FROM_BACKGROUND,
                OnAppReturnsFromBackground);
        }

        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            LogUtils.LogMessage(LogSeverity.INFO, "User opened DiseaseRate", null);
        }

        private void SetStyling()
        {
            // Labels dependable on device width
            double width = DeviceDisplay.MainDisplayInfo.Width;
            int fontMin = width <= 700 ? 18 : 23;
            int fontMax = width <= 700 ? 20 : 25;
            StyleUtil.InitLabelWithSpacing(DiseaseRateNumber1Lbl, StyleUtil.FontType.FontRegular, ConfirmedCasesToday,
                1.14, fontMin, fontMax, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(DiseaseRateNumber2Lbl, StyleUtil.FontType.FontRegular, DeathsToday, 1.14,
                fontMin, fontMax, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(DiseaseRateNumber3Lbl, StyleUtil.FontType.FontRegular, TestsConductedToday,
                1.14, fontMin, fontMax, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(DiseaseRateNumber4Lbl, StyleUtil.FontType.FontRegular, VaccinatedFirst, 1.14,
                fontMin, fontMax, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(DiseaseRateNumber4DescriptionLbl, StyleUtil.FontType.FontRegular,
                KEY_FEATURE_FOUR_FIRST_VACCINATION_LABEL, 1.14, fontMin - 4, fontMax - 4, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(DiseaseRateNumber4SecondLbl, StyleUtil.FontType.FontRegular,
                VaccinatedSecond, 1.14, fontMin, fontMax, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(DiseaseRateNumber4SecondDescriptionLbl, StyleUtil.FontType.FontRegular,
                KEY_FEATURE_FOUR_SECOND_VACCINATION_LABEL, 1.14, fontMin - 4, fontMax - 4, UITextAlignment.Center,
                true);

            StyleUtil.InitLabelWithSpacing(DiseaseRateNumber5Lbl, StyleUtil.FontType.FontRegular,
                SmittestopDownloadsTotal, 1.14, fontMin, fontMax, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(DiseaseRateNumber6Lbl, StyleUtil.FontType.FontRegular,
                NumberOfPositiveTestsResultsLast7Days, 1.14, fontMin, fontMax, UITextAlignment.Center, true);

            // Labels not dependable on device width
            StyleUtil.InitLabelWithSpacing(DiseaseRateLbl, StyleUtil.FontType.FontBold, DISEASE_RATE_HEADER, 1.14, 24,
                36, useHyphenation: true);
            StyleUtil.InitLabelWithSpacing(DiseaseRateOfTheDayTextLbl, StyleUtil.FontType.FontRegular,
                LastUpdateStringSubHeader, 1.14, 12, 14, useHyphenation: true);

            StyleUtil.InitLabelWithSpacing(KeyFeature1Lbl, StyleUtil.FontType.FontBold, KEY_FEATURE_ONE_LABEL, 1.14, 16,
                18, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(TotalDiseaseRateNumber1Lbl, StyleUtil.FontType.FontRegular,
                ConfirmedCasesTotal, 1.14, 12, 14, UITextAlignment.Center, true);
            BackgroundView1.BackgroundColor = UIColor.FromRGB(197, 226, 252);
            BackgroundView1.Layer.CornerRadius = 12;

            StyleUtil.InitLabelWithSpacing(TotalDiseaseRateNumber2Lbl, StyleUtil.FontType.FontRegular, DeathsTotal,
                1.14, 12, 14, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(KeyFeature2Lbl, StyleUtil.FontType.FontBold, KEY_FEATURE_TWO_LABEL, 1.14, 16,
                18, UITextAlignment.Center, true);
            BackgroundView2.BackgroundColor = UIColor.FromRGB(197, 226, 252);
            BackgroundView2.Layer.CornerRadius = 12;

            StyleUtil.InitLabelWithSpacing(TotalDiseaseRateNumber3Lbl, StyleUtil.FontType.FontRegular,
                TestsConductedTotal, 1.14, 12, 14, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(KeyFeature3Lbl, StyleUtil.FontType.FontBold, KEY_FEATURE_THREE_LABEL, 1.14,
                16, 18, UITextAlignment.Center, true);
            BackgroundView3.BackgroundColor = UIColor.FromRGB(197, 226, 252);
            BackgroundView3.Layer.CornerRadius = 12;

            StyleUtil.InitLabelWithSpacing(KeyFeature4Lbl, StyleUtil.FontType.FontBold, KEY_FEATURE_FOUR_LABEL, 1.14,
                16, 18, UITextAlignment.Center, true);
            BackgroundView4.BackgroundColor = UIColor.FromRGB(197, 226, 252);
            BackgroundView4.Layer.CornerRadius = 12;

            StyleUtil.InitLabelWithSpacing(KeyFeature5Lbl, StyleUtil.FontType.FontBold, KEY_FEATURE_SIX_LABEL, 1.14, 16,
                18, UITextAlignment.Center, true);
            BackgroundView5.BackgroundColor = UIColor.FromRGB(197, 226, 252);
            BackgroundView5.Layer.CornerRadius = 12;

            StyleUtil.InitLabelWithSpacing(KeyFeature6Lbl, StyleUtil.FontType.FontBold, KEY_FEATURE_FIVE_LABEL, 1.14,
                16, 18, UITextAlignment.Center, true);
            StyleUtil.InitLabelWithSpacing(TotalDiseaseRateNumber6Lbl, StyleUtil.FontType.FontRegular,
                NumberOfPositiveTestsResultsTotal, 1.14, 12, 14, UITextAlignment.Center, true);
            BackgroundView6.BackgroundColor = UIColor.FromRGB(197, 226, 252);
            BackgroundView6.Layer.CornerRadius = 12;

            StyleUtil.InitUITextViewWithSpacingAndUrl(DiseaseRateSubLbl, StyleUtil.FontType.FontRegular,
                LastUpdateStringSubSubHeader, 1.14, 12, 12);
            DiseaseRateSubLbl.SizeToFit();

            //Setting up accessibility grouping
            ConfirmedCases_StackView.ShouldGroupAccessibilityChildren = true;
            NumberOfDeaths_StackView.ShouldGroupAccessibilityChildren = true;
            NumberOfTests_StackView.ShouldGroupAccessibilityChildren = true;
            PatientsAdmitted_StackView.ShouldGroupAccessibilityChildren = true;
            TotalDownloads_StackView.ShouldGroupAccessibilityChildren = true;
            NumberOfPositiveResults_StackView.ShouldGroupAccessibilityChildren = true;

            BackButton.AccessibilityLabel = SettingsViewModel.SETTINGS_ITEM_ACCESSIBILITY_CLOSE_BUTTON;

            //Implemented for correct voiceover due to smitte|stop, removing pronunciation of lodretstreg
            KeyFeature5Lbl.AccessibilityAttributedLabel =
                AccessibilityUtils.RemovePoorlySpokenSymbols(KEY_FEATURE_SIX_LABEL);

            string contentText = LastUpdateStringSubSubHeader;
            DiseaseRateSubLbl.AccessibilityValue = AccessibilityUtils.RemovePoorlySpokenSymbolsString(contentText);
            DiseaseRateSubLbl.IsAccessibilityElement = true;
        }

        partial void BackButton_tapped(UIButton sender)
        {
            NavigationController.PopViewController(true);
            NavigationHelper.GoToResultPage(this, false);
        }

        private void OnAppReturnsFromBackground(object o)
        {
            InfectionStatusViewModel.RequestSSIUpdate(() => InvokeOnMainThread(SetStyling));
        }
    }
}